#+STARTUP: content indent
* *Apuntes Fundamentos del Software en Linux*
** Distribucion de la memoria en C
|----------------------------------------------+-----------------------------|
| Argumentos del shell y variables del entorno | \leftarrow *High address*   |
|----------------------------------------------+-----------------------------|
| STACK                                        | \leftarrow Memoria estatica |
|----------------------------------------------+-----------------------------|
| HEAP                                         | \leftarrow Memoria dinamica |
|----------------------------------------------+-----------------------------|
| BSS: Datos no inicializados                  |                             |
|----------------------------------------------+-----------------------------|
| Datos inicializados                          |                             |
|----------------------------------------------+-----------------------------|
| Texto                                        | \leftarrow *Low address*    |
|                                              |                             |
|----------------------------------------------+-----------------------------|
                                   
** Memoria Dinamica y Estatica
    
*** Punteros
**** Punteros en C++
#+BEGIN_SRC C++ -n
int *p = new int; // Va al Stack. Su tamanyo se sabe al compilar
delete p; // Borra p y libera la memoria
const int T = 10;
int *p = new int[T]; // Reserva espacio para 10 enteros
delete []p; // Borra y libera lo anterior
#+END_SRC		      	
**** Punteros en C	       
***** - Con malloc()  
#+BEGIN_SRC C -n		      
int *p = (int *)malloc(sizeof(int)); // Alojamos 1 int
/* Como malloc pide la cantidad d  memoria a reservar y esta
 * varia entre maquinas tenemos que utilizar sizeof() */

#define T 10;
int *q = (int *)malloc(T*sizeof(int)); // Alojamos T ints

#+END_SRC
***** - Con calloc()
malloc() asigna memoria sin quitar la basura. calloc() sin embargo
se encarga de inicializar la memoria a '\0'.

#+BEGIN_SRC C -n
#define T 10;
int *q = (int *)calloc(T,sizeof(int)); // Alojamos T ints
free(q); // Libera la memoria
#+END_SRC

Un ejemplo:

#+BEGIN_SRC C -n
int x = 10; // Stack
int **p; // Stack
p = (int **)malloc(sizeof(int *)); // Heap. Nos devuelve una direccion
                                   // en la que cabe un puntero a int
*p = &x; // Asigna la direccion de x a la zona donde apunta p
/* Tenemos una zona del stack que apunta a heap que apunta a stack
 
      +----------------------+
    x |         10           |<----------+
      |----------------------| 		 |
      |                      | 		 |
      |                      | 		 |
      |       STACK          | 	         |
      |----------------------|	         |
    p |                      |------|    |
      +----------------------+      |    |
      |                      |      |    |
      |       HEAP           |      |    |
      |                      |      |    |
      |----------------------|      |    |
malloc|                      |\ <---+    |
      +----------------------+ \         |
			        \        |
				 --------+
*/   
  **p = 30; // Asignamos 30 a x
//||
//|+------> Va a donde apunta p->Heap
//+--------> Va a donde apunta esa zona de Heap -> x
   
#+END_SRC            
***** Ejemplo de aritmetica con punteros
Ejemplo realizado en clase:
#+BEGIN_SRC C
int a[5];
int *p = a;
*p = 10;
//|     |  0 | 1 | 2 | 3 | 4 |
//|-----+----+---+---+---+---|
//|   a | 10 |   |   |   |   |

p++;
*p = 20;

//|     |  0 |  1 | 2 | 3 | 4 |
//|-----+----+----+---+---+---|
//|   a | 10 | 20 |   |   |   |

p = &a[2];
*p = 30;
p = a + 3;
*p = 40 

//|     |  0 |  1 |  2 |  3 | 4 |
//|-----+----+----+----+----+---|
//|   a | 10 | 20 | 30 | 40 |   |

p = a;
*(p + 4) = 50;
//|     |  0 |  1 |  2 |  3 |  4 |
//|-----+----+----+----+----+----|
//|   a | 10 | 20 | 30 | 40 | 50 |
#+END_SRC
**** Punteros a structs
#+BEGIN_SRC C -n
struct x{
	int dato1;
	int dato2;
};
struct x *p = (struct x *)malloc(sizeof(struct x));
(*p).dato1 = 5;
p->dato2 = 10;
#+END_SRC
**** Punteros a funciones
Son punteros a segmetos del data, que es la parte de la memoria en
la que esta el codigo fuente.
/El nombre de una funcion es un puntero a la zona de memoria donde
esta almacenada dicha funcion./
Ejemplo: 
#+BEGIN_SRC C -n
int f(int a, int b); // Suma
int g(int a, int b; //Resta

int (*punteroFuncion)(int, int);
/* Estamos declarando un puntero a una funcion en la que entran 2
 * int y devuelve tambien un int. */
punteroFuncion = f;
punteroFuncion(3, 4); // Devuelve 7, ya que apunta a f
punteroFuncion = g;
punteroFuncion(3, 4); // Devuelve -1, ya que apunta a g
#+END_SRC
*** Repaso rapido de punteros
#+BEGIN_SRC C -n
int *p; // Va al Stack
int x = 10; // Va al Stack
p = &x; // Va al stack. p ahora apunta a x
*p = 20; // Va donde apunta p y asigna 20
printf("%d", x); // Imprime 20
#+END_SRC
*** Pasar argumentos a funciones
| Tipo           | C  | C++ | Descripcion                       |
|----------------+----+-----+-----------------------------------|
| Por valor      | Si | Si  | Copia la variable y pasa la copia |
| Por referencia | No | Si  | Pasa la variable                  |
| Por direccion  | Si | Si  | Pasa un puntero a la variable     |
|----------------+----+-----+-----------------------------------|

**** Ejemplo por valor
#+BEGIN_SRC C -n
void doble(int i){
	i = i + i;
}
int main() {
	int x = 5;
	doble(x); // Manda una copia de x a doble
	printf("%d", x); // Imprime 5
}
#+END_SRC
**** Ejemplo por referencia
Solo en C++
#+BEGIN_SRC C -n
void doble(int &i){
	i = i + i;
}

int main(){
	int x = 5;
	doble(x);
	printf("%d", x); // Imprime 5
}
#+END_SRC

**** Ejemplo por direccion
#+BEGIN_SRC C -n
void doble(int *i){ // Entra un puntero
 	*i = (*i) + (*i);
} 
int main(){
	int x = 5;
	doble(&x);
	printf("%d", x); // Imprime 10
}
#+END_SRC

Otro ejemplo:

#+BEGIN_SRC C -n
void asignar(**i){
	*i = (int **)malloc(sizeof(int x)); // Asigna memoria en Heap
	**i = 7;
}

int main(){
	int *x;
	doble(&x);
	printf("%d",x); // Imprime 7
	free(x); // Liberamos memoria
}
#+END_SRC
**** Array como argumento

En C, el paso como argumento de un array es un puntero a la primera posicion del array.
El identificador de un array es un puntero constante a la primera pos del mismo.
Ejemplo:
#+BEGIN_SRC C -n
int a[3];

void f(int *a);
void f(int a[]);
//Ambas maneras de declarar la funcion son correctas

f(a); // Entra por valor
#+END_SRC
** Procesos
*** Senyales
Son codigos que se mandan a otros procesos para indicar condiciones varias, como 
puede ser cerrar el programa, realizar una accion, alarmas...
Al llegar una senyal a nuestro proceso, el manejador asociado a dicha senyal
se ejecuta. Si no volvemos a asignar ningun manejador a esta senyal, la siguiente
vez que llegue no pasara nada. Para la lista completa consultar el manual.
Se declaran de la siguiente manera:
#+BEGIN_SRC C 
signal(int signo, manejador);
#+END_SRC
Un ejemplo de su uso seria:
#+BEGIN_SRC C 
// Declaramos el manejador de la senyal
void manejador(int signo){
    printf("Ha llegado la senyal\n");
    signal(SIGUSR1, manejador); // Volvemos a asignarle el manejador a la senyal
}
int main(){
    signal(SIGUSR1, manejador); // Asignamos el manejador a la senyal
    pause(); // Esperamos a que llegue una senyal (cualquiera)
}
#+END_SRC

** Manejo del tiempo
*** Alarm
Programa un temporizador. Si anyadimos un pause() esperara una senyal.
La senyal que manda alarm al terminar es SIGALRM. A continuacion se muestra
un pequenyo ejemplo de un temporizador periodico. Este temporizador producira
una senyal SIGALRM cada 5s.
#+BEGIN_SRC C
  void manejador(int signal){
        alarm(5);
	      signal(SIGALRM, manejador);
    }
  int main(){
        signal(SIGALRM, manejador);
        alarm(5);
	      while(1){
	          pause();
	      }
  }    
#+END_SRC
El inconveniente que presenta esta manera es que hay un delay considerable debido
al tiempo de ejecucion, por lo que se va acumulando inexactitud.

*** Temporizadores
A continuacion veremos los temporizadores y los distintos valores de tiempo que pueden
dar.
#+BEGIN_SRC C
int setitimer(int tipo, const strcut itimerval *value, struct itimerval *anterior);
#+END_SRC
| Tipo           | Senyal    | Tiempo que cuenta                                                         |
|----------------+-----------+---------------------------------------------------------------------------|
| ITIMER_REAL    | SIGALRM   | Todo el tiempo que transcurre                                             |
| ITIMER_VIRTUAL | SIGVTALRM | Solamente el tiempo durante el cual el proceso se ejecuta                 |
| ITIMER_PROF    | SIGPROF   | El tiempo de ejecucion del proceso y *tambien de sus llamadas al sistema* |

Podemos afirmar que: Treal > Tprof > Tvirtual
Que puede devolver?
- -1 cuando peta
- 0 cuando ejecuta correctamente

Como es su estructura? 
	#+BEGIN_SRC C
	struct itimerval{
	    struct timerval it_value; // Cuando se produce el primer disparo
	    struct timerval it_interval; // Cuando se produce el siguiente
	}

	
	struct timeval{
	    long tv_sec;  // Segundos
	    long tv_usec; // Microsegundos - S/1,000,000
	}
	#+END_SRC 

