/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


#include <stdio.h>
#include <stdlib.h>
#define MAX 4000000
int main(){
 int sumTotal = 0;
 int current = 1;
 int last = 0;

 printf("Fibonacci Sequence: ");
 while(current < MAX){
  if(current + last > MAX){break;}
  int aux = last;
  last = current;
  current += aux;
  if(current % 2 == 0){
    sumTotal += current;
    
  }
  printf("%d ", current);
 }
 printf("\n");
 printf("Total is: %d \n", sumTotal);
 return 0;
}
